apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: argocd
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: 6.1.5
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: argocd
      interval: 1m
  values:
    replicaCount: 2
