---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-apps
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-apps
  namespace: flux-apps
spec:
  prune: true
  interval: 2m
  path: ./demo/artifacts/flux-apps
  sourceRef:
    kind: GitRepository
    name: fsa-demo
    namespace: flux-system
  timeout: 10m
  wait: true
