apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: fsa-demo
  namespace: flux-system
spec:
  interval: 30s
  # Change url to your forked gitrepo e.g, https://github.com/GitHubUserID/flamingo
  url: https://github.com/drazul/flamingo-test.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fsa-demo
  namespace: flux-system
spec:
  prune: true
  interval: 2m
  path: "./demo"
  sourceRef:
    kind: GitRepository
    name: fsa-demo
  timeout: 3m
